### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by szmeti** [fjudith/docker-alfresco#1]
Hi!

It would be great to use minor version numbers for new images (e.g. 201707.1, 201707.2).

We have been using 201707 for a while now, but the tag has been overwritten and now it is impossible to fetch the image that we were working with.

**Comment by fjudith** [comment]
hello sorry for the inconvenience. The repo as been updated to enabe the CI/CD of both single and microservices containers all running am64/debian. the equivalent to the old version is the Slim Dockerfile. I'm thinking to reorganize the branch to better support upcoming releases of Alfresco EA/GA

**Comment by thinkernel** [comment]
Hi @fjudith 
We have the same problem here. It would be great if you can provide a  fjudith/alfresco:slim on your docker hub site.
I checked your compose file. I found that you've separated the alfresco image into several microsevices images by using docker image tags to define them like fjudith/alfresco:libreoffice, fjudith/alfresco:repository etc. I think that might be a bad idea. Tags are used to track the versions of the target product. To name the image like fjudith/alfresco-libreoffice:201707, fjudith/alfresco-repository:201707 might be an easier way.

**Comment by fjudith** [comment]
Hello @thinkernel,

Travis-CI has been fixed.
`lastest` and `slim` tags available again.

Following your recommandation, micro-services version have now dedicated repositories.

fjudith/alfresco-libreoffice (https://hub.docker.com/r/fjudith/alfresco-libreoffice)
fjudith/alfresco-repository (https://hub.docker.com/r/fjudith/alfresco-repository)
fjudith/alfresco-search (https://hub.docker.com/r/fjudith/alfresco-search)
fjudith/alfresco-share (https://hub.docker.com/r/fjudith/alfresco-share)

Thanks again for your feedback.

**Comment by thinkernel** [comment]
Hi @fjudith 
Awesome! I'll check it ASAP. 
Really appreciate your great works.
